eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/students/**
          - id: courses
            uri: http://localhost:9090
            predicates:
              - Path=/api/courses/**